/*
 * Copyright (C) 2010-2011 VTT Technical Research Centre of Finland.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation;
 * version 2.1 of the License.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

package fi.vtt.noen.mfw.bundle.server.shared.datamodel;

import fi.vtt.noen.mfw.bundle.common.DataObject;
import fi.vtt.noen.mfw.bundle.common.DataType;

import java.io.Serializable;
import java.text.DateFormat;
import java.util.Date;

/**
 * Data value for a measurement.
 * Annotations are for persistence with JPA (DB storage).
 *
 * @author Teemu Kanstren
 */
public class Value extends DataObject implements Serializable {
  //generated by JPA, unique identifier
  private Long id;
  private BMDescription bm;
  //we have a separate precision here to tell the exact precision of this value when it was measured..
  private int precision;
  //the actual value, only strings are supported now
  private String value;
  //time of measurement
  private Date time;
  //subscriptionId to identify every measurement request/response subscription
  //to support the use of multiple SACs
  //this value is not stored in the DB, since historically it has not meaning
  private Long subscriptionId;
  private boolean error;

  public enum SortKey {
    PRECISION, MEASUREURI, VALUE, TIME
  }

  public Value() {
    super(DataType.STRINGVALUE);
  }
  
  public Value(BMDescription bm, int precision, String value, long time) {
    this(bm, precision, value, time, -1);
  }

  public Value(BMDescription bm, int precision, String value, long time, long subscriptionId) {
    this(bm, precision, value, time, subscriptionId, false);
  }

  public Value(BMDescription bm, int precision, String value, long time, long subscriptionId, boolean error) {
    super(DataType.STRINGVALUE);
    this.bm = bm;
    this.precision = precision;
    this.value = value;
    this.time = new Date(time);
    this.subscriptionId = subscriptionId;
    this.error = error;
  }
  
  public long getSubscriptionId() {
    return subscriptionId;
  }

  public String getMeasureURI() {
    return bm.getMeasureURI();
  }

  public long getId() {
    return id;
  }

  public BMDescription getBm() {
    return bm;
  }

  public int getPrecision() {
    return precision;
  }

  public String getString() {
    checkType(DataType.STRINGVALUE);
    return value;
  }

  public Date getTime() {
    return time;
  }

  public boolean isError() {
    return error;
  }

  public String getTimeFormatted() {
    return DateFormat.getDateTimeInstance().format(time);
  }

  private void checkType(DataType expected) {
    if (getType() != expected) {
      throw new IllegalArgumentException("Not " + expected + " type value (actually " + getType() + ").");
    }
  }

  @Override
  public String toString() {
    return bm.getMeasureURI() + ":" + value;
  }

  public String valueString() {
    if (getType() == DataType.STRINGVALUE) {
      return "\""+value+"\"";
    }
    return "" + value;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;

    Value value1 = (Value) o;

    if (precision != value1.precision) return false;
    if (bm != null ? !bm.equals(value1.bm) : value1.bm != null) return false;
    if (time != null ? !time.equals(value1.time) : value1.time != null) return false;
    if (value != null ? !value.equals(value1.value) : value1.value != null) return false;
    if (subscriptionId != value1.subscriptionId) return false;

    return true;
  }

  @Override
  public int hashCode() {
    int result = bm != null ? bm.hashCode() : 0;
    result = 31 * result + precision;
    result = 31 * result + (value != null ? value.hashCode() : 0);
    result = 31 * result + (time != null ? time.hashCode() : 0);
    result = 31 * result + subscriptionId.hashCode();
    return result;
  }
}
